### ISSUE TITLE
bluebinder spams logcat on Android 10 device

### ISSUE THREAD

**Issue by Flohack74** [mer-hybris/bluebinder#20]
With the SHIFT 6mq, Ubuntu Touch as OS I get these logs all the time:

```
01-24 10:38:49.464   235  1225 I vendor.qti.bluetooth@1.0-ibs_handler: ProcessIbsCmd: Received IBS_SLEEP_IND: 0xFE
01-24 10:38:49.464   235  1225 D vendor.qti.bluetooth@1.0-ibs_handler: SerialClockVote: vote for UART CLK OFF
01-24 10:38:49.493   235  1225 I vendor.qti.bluetooth@1.0-ibs_handler: ProcessIbsCmd: Received IBS_WAKE_IND: 0xFD
01-24 10:38:49.493   235  1225 D vendor.qti.bluetooth@1.0-ibs_handler: SerialClockVote: vote for UART CLK ON
01-24 10:38:49.493   235  1225 I vendor.qti.bluetooth@1.0-ibs_handler: ProcessIbsCmd: Writing IBS_WAKE_ACK
01-24 10:38:49.536   235  1225 I vendor.qti.bluetooth@1.0-ibs_handler: ProcessIbsCmd: Received IBS_SLEEP_IND: 0xFE
01-24 10:38:49.536   235  1225 D vendor.qti.bluetooth@1.0-ibs_handler: SerialClockVote: vote for UART CLK OFF
01-24 10:38:49.543   235  1225 I vendor.qti.bluetooth@1.0-ibs_handler: ProcessIbsCmd: Received IBS_WAKE_IND: 0xFD
01-24 10:38:49.543   235  1225 D vendor.qti.bluetooth@1.0-ibs_handler: SerialClockVote: vote for UART CLK ON
01-24 10:38:49.543   235  1225 I vendor.qti.bluetooth@1.0-ibs_handler: ProcessIbsCmd: Writing IBS_WAKE_ACK
```

A closer inspection with strace in bluebinder yields:
```
[pid  4512] ppoll([{fd=4, events=POLLIN|POLLERR|POLLHUP|POLLNVAL}, {fd=5, events=POLLIN|POLLERR|POLLHUP|POLLNVAL}], 2, NULL, NULL, 0) = 1 ([{fd=4, revents=POLLIN}])
[pid  4512] ioctl(4, BINDER_WRITE_READ, 0x7f8c2b87c8) = 0
[pid  4512] write(3, "\1\0\0\0\0\0\0\0", 8) = 8
[pid  4504] <... ppoll resumed> )       = 1 ([{fd=3, revents=POLLIN}])
[pid  4512] ppoll([{fd=5, events=POLLIN|POLLERR|POLLHUP|POLLNVAL}, {fd=8, events=POLLIN|POLLERR|POLLHUP|POLLNVAL}], 2, NULL, NULL, 0 <unfinished ...>
[pid  4504] read(3, "\1\0\0\0\0\0\0\0", 16) = 8
[pid  4504] write(10, "\4>+\2\1\3\1\302;7\365\2016\37\2\1\32\3\3o\375\27\26o\375^\210h\315#Y\244"..., 46) = -1 ENXIO (No such device or address)
[pid  4504] write(2, "Writing packet to device failed:"..., 59) = 59
[pid  4504] write(9, "*", 1 <unfinished ...>
[pid  4512] <... ppoll resumed> )       = 1 ([{fd=8, revents=POLLIN}])
[pid  4504] <... write resumed> )       = 1
[pid  4512] read(8,  <unfinished ...>
[pid  4504] ppoll([{fd=3, events=POLLIN}, {fd=10, events=POLLIN}], 2, NULL, NULL, 0 <unfinished ...>
[pid  4512] <... read resumed> "*", 1)  = 1
[pid  4512] ioctl(4, BINDER_WRITE_READ, 0x7f8c2b86d8) = 0
[pid  4512] ioctl(4, BINDER_WRITE_READ, 0x7f8c2b8678) = 0
[pid  4512] ioctl(4, BINDER_WRITE_READ, 0x7f8c2b8678) = 0
[pid  4512] ioctl(4, BINDER_WRITE_READ, 0x7f8c2b8758) = 0
```

So bluebinder is relaying writes to devices that are no longer visible. Also it does not matter if Bluetooth is turned on or of. This behaviour will slowly build up after boot since more and more devices are seen.

This is unique to that device so far, but its also my first Android 10 device. Any hint for debugging welcome!

**Comment by Flohack74** [comment]
This also severly impacts battery life.

**Comment by krnlyng** [comment]
Writing packet to device failed: comes from here:
https://github.com/mer-hybris/bluebinder/blob/master/bluebinder.c#L168

it looks like bluetooth has been turned off but something is still wanting to send data to the device?

**Comment by krnlyng** [comment]
What kind of devices do you mean by: "will slowly build up after boot since more and more devices are seen."

**Comment by Flohack74** [comment]
In my gut feeling its **all** devices that HCI interface has **ever seen**:
![grafik](https://user-images.githubusercontent.com/16186470/150779291-1d00df20-9162-4296-9015-a3b2f409c84d.png)
Its just lots of different addresses....

**Comment by Flohack74** [comment]
Well now I killed Bluez daemon and still those messages are appearing. How can I find out who is bugging bluebinder to send those messages?

**Comment by krnlyng** [comment]
Ah sorry it's actually the other way around. Bluetooth seems to be disabled from bluez perspective but the HAL "didn't get the message" and still is trying to send stuff to the host.

**Comment by krnlyng** [comment]
> Ah sorry it's actually the other way around. Bluetooth seems to be disabled from bluez perspective but the HAL "didn't get the message" and still is trying to send stuff to the host.

It might be that we need to implement an rfkill listener and call close/open dynamically when the rfkill soft state for our bluetooth device is changed. But i'm not yet 100% sure about that.

**Comment by Flohack74** [comment]
Yeah that might the case ^^ so, can I confirm this somehow and what can be done about it

**Comment by krnlyng** [comment]
> Yeah that might the case ^^ so, can I confirm this somehow and what can be done about it

Well after looking more closely i think your logs are already proof of that. But you could try capturing a strace from *before* turning bluetooth off until after.

**Comment by Flohack74** [comment]
Alrighty so its a bug in the underlying HAL or in bluebinder?

**Comment by krnlyng** [comment]
Most likely bluebinder.

**Comment by Flohack74** [comment]
But I am confused by ""Writing packet to device failed:"..., 59) = 59" - wouldnt that mean the transfer started on host/UT side?

**Comment by krnlyng** [comment]
> But I am confused by ""Writing packet to device failed:"..., 59) = 59" - wouldnt that mean the transfer started on host/UT side?

I agree the error message is confusing, it means "Writing packet from HAL to virtual vhci device failed"

**Comment by Flohack74** [comment]
Oki understood. So, does bluebinder in some way keep track of devices in some internal records or where do they come from

**Comment by krnlyng** [comment]
> Oki understood. So, does bluebinder in some way keep track of devices in some internal records or where do they come from

As said it's only one device which it gets confused about, i.e. the virtual vhci device. not actual bluetooth devices on the air.

**Comment by Flohack74** [comment]
Ah ok I see so VHCI device is down on the bus, but it still tries to send stuff there. So I am glad to help if anything can be debugged on this one ;)

**Comment by krnlyng** [comment]
> Ah ok I see so VHCI device is down on the bus, but it still tries to send stuff there. So I am glad to help if anything can be debugged on this one ;)

I might have an idea how to solve it. Will try it later.

**Comment by krnlyng** [comment]
Could you try this? https://github.com/krnlyng/bluebinder-1/tree/jb51155

I tried to listen to both rfkill events and close/open the device dynamically based on that but i ran into various issues.

The PR above just listens to rfkill disabling of the bluetooth device and resets the device if a event is received after the device is considered shut down.

**Comment by Flohack74** [comment]
Alright will do thx!

**Comment by krnlyng** [comment]
Just to clarify, the message might still appear once or twice in the logs when turning bluetooth off. but it should not persist as before if my theory is correct.

**Comment by Flohack74** [comment]
Yeah that's understandable. I took the patch in (unfortunately we have a fork now and I could not apply 1:1 but I think I got the relevant parts), and first look is good. I let you know in a few days.

**Comment by Flohack74** [comment]
Just a snippet from strace
![grafik](https://user-images.githubusercontent.com/16186470/150877881-f7b61ee3-9e73-4d4b-b3e2-3d90a9ff0c63.png)

**Comment by Flohack74** [comment]
So after that its silence when I switch off :)

**Comment by krnlyng** [comment]
@Flohack74 Just one more
https://github.com/mer-hybris/bluebinder/commit/b0a7cb53639c3327968fbe109ce7d87aad85c415

this one might work better in terms of battery consumption.

**Comment by Flohack74** [comment]
Alright I assume thats the one you proposed for merging? :)

**Comment by krnlyng** [comment]
Yes

**Comment by Flohack74** [comment]
Alright, I wont re-test it now since we have to rebase our stuff first on latest master, but I follow-up as soon as its in on your side

**Comment by krnlyng** [comment]
Can we close this now?

**Comment by krnlyng** [comment]
> Alright, I wont re-test it now since we have to rebase our stuff first on latest master, but I follow-up as soon as its in on your side

Also sounds like you have diffs. Please upstream it if possible.

**Comment by Flohack74** [comment]
Gimme 1 day to test it, run it through our CI nightly build, and then update tomorrow, and I recheck it :)

We have basically the following changes:
- Debian packaging
- upstart: Stop service at runlevel 0 and 6 - Should fix the system-watchdog triggering a reboot whenever
the bluebinder service fails to stop cleanly at shutdown. Maybe this is irrelevant for you and it also wont apply on systemd
- Check for versioned bluetooth service (#5) - On the JingPad the vendor service on the Halium side has a version
number appended on the service identifier. This needs extension of the regex that waits for the service to be running

If you indicate to me whats useful we can upstream those, sure.

**Comment by Flohack74** [comment]
@krnlyng I am afraid some users reported a regression from the fix you made on a Vollaphone with Halium 9 = Android 9 hybris level. While this device was okay before, I just got this log. Initially, BT is off, and then bluebinder spams again. Turning BT on stops the spam, and also turning it off keeps silence. So its smth to do with the initial availability of the device or idk.
If BT was on and then a reboot is done the condition seems not to be there.
For details see https://pastebin.com/xBsWHE8P

**Comment by krnlyng** [comment]
This looks like the intiialization sequence failed.
Can you paste the output of hciconfig when that happens?

**Comment by krnlyng** [comment]
https://github.com/mer-hybris/bluebinder/blob/master/bluebinder.c#L687
If you remove the memcmp from there it will probably work.
However it will not initialize the bluetooth MAC until you switch bluetooth on for the first time.

**Comment by luksus42** [comment]
> Can you paste the output of hciconfig when that happens?

A MAC address seems to be there:
```
phablet@ubuntu-phablet:~$ hciconfig
hci0: Type: Primary Bus: Virtual
BD Address: 84:CF:BF:8E:43:A9 ACL MTU: 1024:7 SCO MTU: 50:8
DOWN
RX bytes:0 acl:0 sco:0 events:33 errors:0
TX bytes:423 acl:0 sco:0 commands:33 errors:0

phablet@ubuntu-phablet:~$ hciconfig 
hci0: Type: Primary Bus: Virtual
BD Address: 84:CF:BF:8E:43:A9 ACL MTU: 1024:7 SCO MTU: 50:8
UP RUNNING PSCAN
RX bytes:0 acl:0 sco:0 events:74 errors:0
TX bytes:1194 acl:0 sco:0 commands:74 errors:0

phablet@ubuntu-phablet:~$ hciconfig
hci0: Type: Primary Bus: Virtual
BD Address: 84:CF:BF:8E:43:A9 ACL MTU: 1024:7 SCO MTU: 50:8
DOWN
RX bytes:0 acl:0 sco:0 events:76 errors:0
TX bytes:1207 acl:0 sco:0 commands:76 errors:0

phablet@ubuntu-phablet:~$
```
The first hciconfig output is after normal boot, when bluebinder is consuming 99% cputime.
The second one after enabling Bluetooth.
The third one after disabling Bluetooth again.
-> bluebinder cputime is normal again / process is not running anymore.

(btw. now Bluetooth is working after enabling it, when booted with disabled Bluetooth. On a prior test, I needed to enable Bluetooth and the restart to make it work. But that may be an Ubuntu Touch specific issue...)

**Comment by krnlyng** [comment]
What if you change (in only the mentioned line) HCI_UP to HCI_RUNNING. e.g
```
    if ((hci_test_bit(HCI_UP, &di.flags) && !hci_test_bit(HCI_INIT, &di.flags))
        || (!hci_test_bit(HCI_RUNNING, &di.flags) && memcmp(&zero_bdaddr, &di.bdaddr, sizeof(bdaddr_t) != 0))) {
```

**Comment by krnlyng** [comment]
https://github.com/mer-hybris/bluebinder/pull/26

**Comment by luksus42** [comment]
> What if you change (in only the mentioned line) HCI_UP to HCI_RUNNING. e.g
> 
> ```
>     if ((hci_test_bit(HCI_UP, &di.flags) && !hci_test_bit(HCI_INIT, &di.flags))
>         || (!hci_test_bit(HCI_RUNNING, &di.flags) && memcmp(&zero_bdaddr, &di.bdaddr, sizeof(bdaddr_t) != 0))) {
> ```

uhm, I am currently not prepared to recompile it for my phone/arm64... @Flohack74 how about you?

**Comment by Flohack74** [comment]
We can run it in our CI and make installable packages. Lets see if I can do this during this WE still...

**Comment by Flohack74** [comment]
@krnlyng it seems that fixes the problem, but interestingly already with the commit before your parenthesis fix ^^ so very likely it was commit on Apr 14th or so. But, seems also with the PR branch it works, at least for one reporting user.
I guess you could merge #26 and we rebase, and put it into our devel image.

**Comment by Flohack74** [comment]
We have rolled this out now in our OTA and so far spamming seems gone. We got another issue now with one device (see #28 ) but this one here I can close. Thx!
